### PR TITLE
Added a post for playtest-20150628

### PR DESCRIPTION
**Pull request by Mailaender**
Basically @pchote's post, just added Soviet02 and the screenshot hotkey.

### CODE REVIEW

**Comment by GraionDilach** [comment]
(y)

**Comment by penev92** [comment]
:+1:

**Comment by Mailaender** [comment]
The [Lua API diff](https://github.com/OpenRA/OpenRA/wiki/Lua-API-(playtest)/_compare/4ca56a22c0ee420ab10bc19779d0a7d95be87b85...e0191a3cd9f569d56a95fa1625ce919f8524ae5e) did not time out this time.

**Comment by Mailaender** [comment]
Updated the RPM: https://build.opensuse.org/package/rdiff/games:openra/playtest?linkrev=base&rev=21

**Pull request merged**
