### PR TITLE
Added the chocolatey repository

### PR DESCRIPTION
**Pull request by Mailaender**
https://chocolatey.org/packages/openra/ is automatically updated via a robot by @dtgm based on the templates in https://github.com/OpenRA/Chocolatey repository.

### CODE REVIEW

**Comment by penev92** [comment]
That page says it was last updated more than an year ago  :?

**Comment by pchote** [comment]
The previous and current releases are bogged down in their moderation queue, and so it currently points to a development version from over a year ago.  We may have to wait another week or two for the packages to be reviewed, and can then merge this after it has been updated.

**Comment by Mailaender** [comment]
@AnthonyMastrean Can you disable moderation for the OpenRA package or let us review submissions instead?

**Comment by AnthonyMastrean** [comment]
Let me review the rules for exempt packages/maintainers... we might need to get a few through moderation first. You know, since your team is on top of submissions now, why not remove me from the list (I can't remove myself) and I'll get a few through?

**Comment by AnthonyMastrean** [comment]
Nevermind, I was able to remove myself from the maintainers list :)

**Comment by AnthonyMastrean** [comment]
The "trusted" package section says

> * Trusted package ids are packages where we have built trust in the package maintainer(s).
> * This usually happens after we have seen several iterations of a package without issues.
> * All package *versions* submitted from now on will automatically be approved.
> * This also happens when maintainer is the author of the software.

This package is good, the maintainers are good, I'll mark this one trusted right away!

**Comment by Mailaender** [comment]
Thanks!

**Comment by donno** [comment]
Recently tried installing the openra package (v2015.09.19) via Chocolatey (v0.9.9.8) and received the following error:
```
Checksum for
 'C:\Users\Donno\AppData\Local\Temp\chocolatey\openra\openraInstall.exe' did
 not meet 'b7c38fbba90793bef5cda28de1bc6bcd' for checksum type 'md5'.
 At C:\ProgramData\chocolatey\helpers\functions\Get-CheckSumValid.ps1:51 char:5
 +     throw "Checksum for `'$file'` did not meet `'$checksum`' for chec ...
 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (Checksum for 'C...sum type 'm 
    d5'.:String) [], RuntimeException
     + FullyQualifiedErrorId : Checksum for 'C:\Users\Donno\AppData\Local\Temp\ 
    chocolatey\openra\openraInstall.exe' did not meet 'b7c38fbba90793bef5cda28  
   de1bc6bcd' for checksum type 'md5'.
The install of openra was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\openra\tools\chocolateyInstall.ps1'.
 See log for details.
```

Looking at the given path:
```
$ md5sum openraInstall.exe
bb5dcc43446f5ed907e79b271fbc1834 *openraInstall.exe
```

It reported it was downloading the executable from https://github.com//OpenRA/OpenRA/releases/download/release-20150919/OpenRA-release-20150919.exe which I downloaded with curl and md5sum that and it resultined in bb5dcc43446f5ed907e79b271fbc1834 *OpenRA-release-20150919.exe

Hope that helps in resolving the issue.

**Comment by AnthonyMastrean** [comment]
Oh, that's no good... I only tested OpenRA 2015.06.14 before trusting/accepting the package. You're right that the checksum for the latest version is different.

```
$ md5sum OpenRA-release-20150919.exe
bb5dcc43446f5ed907e79b271fbc1834 *OpenRA-release-20150919.exe
```

**Comment by Mailaender** [comment]
Reported it at https://github.com/dtgm/chocolatey-packages/issues/57 as there is nothing we can do to fix it.

**Comment by Mailaender** [comment]
As no one seems to react I filed https://github.com/dtgm/chocolatey-packages/pull/72 on my own to resolve this.

**Comment by ferventcoder** [comment]
Hopefully it gets resolved soon. It's a pain to see a package failing when it should be working.

**Comment by Mailaender** [comment]
https://chocolatey.org/packages/openra/2015.12.24.20151227 is now installable. Thanks @dtgm

**Comment by Mailaender** [comment]
Rebased.

**Comment by ferventcoder** [comment]
Glad that was resolved. Apologies it took longer than expected.

**Pull request merged**
