### PR TITLE
Add new package lists for ra and d2k.

### PR DESCRIPTION
**Pull request by pchote**
For use with https://github.com/OpenRA/OpenRA/pull/11545 and https://github.com/OpenRA/OpenRA/pull/11587.

### CODE REVIEW

**Comment by Mailaender** [comment]
d2k-quickinstall.zip contains a `.DS_STORE` file.

**Comment by pchote** [comment]
That won't affect anything in OpenRA/OpenRA#11587 (it won't be extracted), so it would be good if we can get this merged in the meantime and i'll give @baxxxster an updated file for the mirrors.

**Comment by GraionDilach** [comment]
Thought there's a content mirror on PPM as well, why don't you update that one along?

**Comment by pchote** [comment]
I don't have the details for that server at hand.

**Comment by Mailaender** [comment]
I sent you the login as a private message at http://www.ppmforums.com/

**Comment by Mailaender** [comment]
I now uploaded the files myself. https://github.com/OpenRA/OpenRAWeb/issues/306

**Pull request merged**
