### PR TITLE
Elaborate on the status of the TS mod

### PR DESCRIPTION
**Pull request by obrakmann**
as wished in https://github.com/OpenRA/OpenRAWeb/pull/200#discussion_r27353430

### CODE REVIEW

**Comment by pchote** [comment]
@Phrohdoh noticed that there is a typo ("strucuture") in the first highlight description.  It would be good if you could fix that here too.

**Comment by obrakmann** [comment]
Updated

**Comment by obrakmann** [comment]
@Mailaender: the build error due to a timeout while fetching from github: https://travis-ci.org/OpenRA/OpenRAWeb/builds/56303521

**Comment by obrakmann** [comment]
Rebased onto master

**Pull request merged**
