### PR TITLE
Removed the openra.dxnet.ru mirror

### PR DESCRIPTION
**Pull request by Mailaender**
http://openra.dxnet.ru/ is gone. Looks like unpaid bills. Also notifying @xaionaro.

### CODE REVIEW

**Comment by pchote** [comment]
:+1: but if we merge this while travis is rate limited it will break the website.

**Comment by Mailaender** [comment]
Rebuild on Travis. Seems to be clear now.

**Comment by xaionaro** [comment]
I notified @ihptru about the problem with domains about month ago, IIRC. The problem is indirectly caused by Ukraine crisis… Anyway server still reachable by IP-address (178.63.32.174), but ok :)

**Comment by Mailaender** [comment]
I see. Brought it back in https://github.com/OpenRA/OpenRAWeb/pull/248.

**Pull request merged**
