### PR TITLE
Added mirrors for every package on leamsi.xyz

### PR DESCRIPTION
**Pull request by leamsifigs**
Added mirrors for the following on leamsi.xyz:
d2k-103-packages.zip
d2k-music.zip
ra-music.zip
ra-packages.zip
ts-packages.zip
ts-music.zip

### CODE REVIEW

**Comment by jaZzKCS** [comment]
Wow, every game but you leave out the original CnC: Tiberian Dawn? What a blasphemy...

On a related note, thank you for the mirrors. Albeit the music content for d2k is probably going to get deleted again, since the decision is still against distributing the d2k music until the (c) questions are fully answered by EA (so probably forever).

More information about the d2k music and the decision not to distribute it can be read here:
https://github.com/OpenRA/OpenRA/pull/9162

**Comment by jaZzKCS** [comment]
https://github.com/OpenRA/OpenRAWeb/pull/268

**Comment by jaZzKCS** [comment]
Also this is referring to: https://github.com/OpenRA/OpenRA/pull/9162

**Comment by Mailaender** [comment]
SHA1 matches :white_check_mark: and you host http://leamsi.xyz/openra/cnc-packages.zip but forgot to add it here.

**Comment by leamsifigs** [comment]
@Mailaender Should I make another pull request with these things fixed?

**Comment by Mailaender** [comment]
Or use `git amend` to fix up this one. Whatever suits you.

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/OpenRAWeb/pull/274.

**Pull request closed without merging**
