### PR TITLE
Update cnc-mirrors.txt

### PR DESCRIPTION
**Pull request by koljasagorski**
New Mirror

### CODE REVIEW

**Comment by pchote** [comment]
I've merged all the other prs here and verified that the file checksums match using #469 

All looks good, except that https://mirror.koljasagorski.de/OpenRA.net/ra-score.zip is a 404. If you can fix that I'll confirm and merge.

**Comment by pchote** [comment]
Any progress here @kanet0x? The entire https://mirror.koljasagorski.de subdomain now appears to be offline!

**Comment by koljasagorski** [comment]
Oh man, fuck. I forgot to reply here, I fix it long time ago.

**Comment by abcdefg30** [comment]
The links still give me 404s, please re-open this (or preferably a different PR) once you have time to fix this.

**Pull request closed without merging**
