### PR TITLE
add Docker support

### PR DESCRIPTION
**Pull request by hasufell**
Since I had trouble getting `nanoc` to work and random stuff was missing, I set up a Dockerfile for easier development/testing.

### CODE REVIEW

**Comment by Mailaender** [comment]
Looks like this means we need to upgrade to Ruby 2.2 which I absolutely appreciate as openSUSE Tumbleweed also stopped supporting 2.1 properly.

**Comment by hasufell** [comment]
Well, I don't know how you managed to even build it when two dependencies are missing, or are these not needed with ruby-2.1? I'd rather guess they just "happen" to be installed on e.g. the travis server, but are still missing from the Gemfile.

The docker image uses ruby-2.3, so that works too. I also find it a much easier way to test and deploy, because I don't have to mess with ruby, gems and other problems on the host. Ofc people not familiar with docker might disagree, but it's ofc optional.

**Comment by pchote** [comment]
> Looks like this means we need to upgrade to Ruby 2.2 which I absolutely appreciate as openSUSE Tumbleweed also stopped supporting 2.1 properly.

We investigated that in the past, and found that this then breaks compilation under OSX.

If this is a serious enough problem that we need to consider breaking support for one system in favour of another then I vote for migrating the site over to Jekyll instead.

**Comment by hasufell** [comment]
> We investigated that in the past, and found that this then breaks compilation under OSX.

That won't be a problem either if you use the docker image. [OSX supports docker](https://docs.docker.com/engine/installation/mac/).

**Pull request closed without merging**
