### PR TITLE
Added a new mirror

### PR DESCRIPTION
**Pull request by Alberthaff**

### CODE REVIEW

**Comment by Mailaender** [comment]
Thanks!

**Comment by Alberthaff** [comment]
@Mailaender NP. Do you have a repository that i can mirror on the server, so that new files can be added automatically?

**Comment by Alberthaff** [comment]
@Mailaender NP. Do you have a repository that i can clone onto the mirror-server, so that new files are added automatically?

**Comment by Mailaender** [comment]
I'd say at the moment http://openra.ppmsite.com/ is some kind of master, but I won't invest too much into automation as we don't plan to change those ZIP files again soon.

**Comment by Alberthaff** [comment]
Allright :-)

**Pull request merged**
