### PR TITLE
Removed non-responsive mirrors

### PR DESCRIPTION
**Pull request by Mailaender**
It looks like @xaionaro's Hetzner server is gone and the Russian mirror has DNS problems.

### CODE REVIEW

**Comment by pchote** [comment]
The srvdonate.ut.mephi.ru links work fine for me.

**Comment by xaionaro** [comment]
Should I fix 178.63.32.174 or this's an extra server?

**Comment by xaionaro** [comment]
P.S.: Didn't find any problems with srvdonate.ut.mephi.ru

**Comment by Mailaender** [comment]
> Should I fix 178.63.32.174 or this's an extra server?

It was the http://openra.ipdx.ru webserver before the domain got shut down. https://github.com/OpenRA/OpenRAWeb/pull/248

**Comment by Mailaender** [comment]
Added http://srvdonate.ut.mephi.ru/openra/ as the DNS error seems to be temporarily or happened solely on my side.

**Comment by obrakmann** [comment]
:+1:

**Pull request merged**
