### PR TITLE
Added NixOS, Snap, Solus and Void install instructions

### PR DESCRIPTION
**Pull request by fusion809**
Hi,

This is essentially my closing #394, and adding a few extra package installation instructions.

Thanks for your time,
Brenton

### CODE REVIEW

**Comment by pchote** [comment]
Sorry for taking so long to get to this!

The snap icon appears to be broken in multiple ways: its named `.png` but is actually a svg, and renders incorrectly when fixing the filenames.

IMO the Linux tab is now far too long and text-filled by default for comfort. Can we reorganize into perhaps a "Distro Packages" section, at the same semantic level as AppImages / Flatpak / Snap, with subheadings that are collapsed by default with a click to expand arrow / + symbol?

**Comment by fusion809** [comment]
Fine with me, although I must admit I do not think I know how to do that, my HTML/JS knowledge is quite rudimentary.

**Comment by matjaeck** [comment]
I'll try to help with the markup and js.

**Comment by pchote** [comment]
Alternatively, take a look at how the different platform tabs (windows, macos, linux, etc) work - these are set up to show all options if js is disabled.

**Comment by pchote** [comment]
I have a local branch that implements this on top of a revised download page layout. I will file a new PR that will supersede this once it is complete.

**Comment by pchote** [comment]
See #453.

**Pull request closed without merging**
